#!/bin/bash
# 5-battlefield game w/ memory limit

trap "/usr/bin/killall -q -u $USER ./Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Blotto ]; then
  echo './Blotto is missing or not executable'
  echo './Blotto is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null /usr/bin/valgrind --tool=massif --massif-out-file=massif.out --log-file=valgrind.out ./Blotto --verify --score 1 2 3 4 5 < /c/cs474/hw3/Tests/t014.in
cat stdout.out  | grep PASSED
grep "mem_heap_B" massif.out | cut -d'=' -f2 | /c/cs474/bin/CheckMax "memory limit exceeded: " 1048576
