#!/bin/bash
# Cribbage Pegging Execution Test (succeeds if your program ran)

trap "/usr/bin/killall -q -u $USER ./TestMCTS 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./TestMCTS ]; then
  echo './TestMCTS is missing or not executable'
  echo './TestMCTS is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null ./TestMCTS --game=pegging --count=100 --depth=14 --time=0.01 < /dev/null
cat stdout.out  | grep NET | wc -l
